### ISSUE TITLE
Fix the sign in and sign up links 

### ISSUE THREAD

**Issue by max-programming** [tewarig/torii#3]
## Problem
When the user clicks on either of these links
![image](https://user-images.githubusercontent.com/51731966/126906053-b225973d-82ec-4aaf-9ed4-a3f02a2dfd03.png)
![image](https://user-images.githubusercontent.com/51731966/126906057-04649f0e-77ce-45cd-a9c0-98fa049d0c15.png)

It takes the user to `https://accounts.47eps.xdtzz.lcl.dev/[signinOrSignup]` instead of the main base URL

## Solution

Go to your [Clerk Dashboard](https://dashboard.clerk.dev/), and open your App Settings (https://dashboard.clerk.dev/instances/{YOUR_INSTANCE}/url-settings)

In the URL & Redirects section, change the default settings to these
![image](https://user-images.githubusercontent.com/51731966/126906145-f3b5faa6-d15c-415e-8454-e84bb6c04d99.png)

**Comment by tewarig** [comment]
wow, this really helped me. thanks @max-programming
