### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by itsharshitb** [tewarig/torii#4]
Troii is crashing after 6 to 7 sec of opening. I have used "https://toriii.vercel.app/" in search bar and webapp opened
 successfully. But later on scrolling down within 6 to 7 seconds it is showing something went wrong message. Check the attachment below.
![Capture](https://user-images.githubusercontent.com/53501531/127292437-78464d73-0218-4726-b3a3-05abf4d727e9.PNG)

**Comment by tewarig** [comment]
well, you are trying to open torii in brave. brave does not allows 3-rd party scripts to run that's why this is happening .. try to open it in chrome. 
this website would not work on private window or brave : )
